name: DontStarveMobUpgrades
version: 1.0
author: Noverita
main: me.noverita.mobupgrades.Main
api-version: 1.13
commands:
  fasthunger:
    description: Enables fast hunger
    usage: /fasthunger <interval>
    default: op
  damagebuff:
    description: Changes damage multiplier
    usage: /damagebuff <multiplier>
    default: op
  spawneffect:
    description: Changes on spawn potion effects
    usage: /spawneffect <Entity Type> <Effect Type> <Amplifier>
    default: op